# Day 1


## Till Video 10

# Boolean Variables

In [3]:
False

False

In [5]:
True

True

In [6]:
type(True)

bool

In [7]:
str = 'Shaival Mehta'

In [17]:
print(str.isalnum())
print(str.isalpha())
print(str.islower())
print(str.istitle())
print(str.isupper())
print(str.isspace())
print(str.endswith('a'))
print(str.startswith('S'))

False
False
False
True
False
False
True
True


# List

In [18]:
type([])

list

In [19]:
lst = ['Python','R', 'C', 'C++']

In [21]:
lst[1]

'R'

In [22]:
len(lst)

4

# Append

In [23]:
lst.append('SQL')

In [28]:
lst

['Python', 'PHP', 'R', 'C', 'C++', 'SQL']

In [29]:
lst.append(['Java','Kotlin'])

In [30]:
lst

['Python', 'PHP', 'R', 'C', 'C++', 'SQL', ['Java', 'Kotlin']]

# Insert

In [31]:
lst.insert(1,'PHP')

In [32]:
lst

['Python', 'PHP', 'PHP', 'R', 'C', 'C++', 'SQL', ['Java', 'Kotlin']]

In [33]:
len(lst)

8

# Extend

In [37]:
lst.extend(['.NET'])

In [38]:
lst

['Python', 'PHP', 'PHP', 'R', 'C', 'C++', 'SQL', ['Java', 'Kotlin'], 1, '.NET']

# Remove, Pop

In [39]:
lst.remove(1)

In [40]:
lst

['Python', 'PHP', 'PHP', 'R', 'C', 'C++', 'SQL', ['Java', 'Kotlin'], '.NET']

In [42]:
lst.pop()

'.NET'

In [43]:
lst

['Python', 'PHP', 'PHP', 'R', 'C', 'C++', 'SQL', ['Java', 'Kotlin']]

# Count, Sum, Min, Max

In [45]:
lst1 = [1,2,2,3,4,5,6,7,8,9,2]
lst1.count(2)

3

In [46]:
sum(lst1)

49

In [47]:
min(lst1)

1

In [48]:
max(lst1)

9

# Sets

In [54]:
set_var = set()
print(type(set_var))

<class 'set'>


In [62]:
set_var = {'Ronaldo','Messi','Rooney'}
set_var.add('Bruno')
set_var


{'Bruno', 'Messi', 'Ronaldo', 'Rooney'}

In [84]:
set_var.discard('Rooney')
##set_var.remove('y')

In [85]:
set_var2= {'Rashford','MArtial','Greenword','Ronaldo'}

In [89]:
set_var2.difference_update(set_var)

In [92]:
set_var

{'Bruno', 'Messi', 'Ronaldo'}

# Dictionaries

In [95]:
dicti = {}
type(dict)

dict

In [98]:
dicti = {2,4,6,8,10}

In [99]:
type(dict)

set

In [106]:
dic = {"1":"Ronaldo","2":"Messi","3":"Neymar","4":"Bruno"}
dic.get('1')

'Ronaldo'

In [110]:
for x,y in dic.items():
    print(x,y)

1 Ronaldo
2 Messi
3 Neymar
4 Bruno


In [112]:
dic['2']='Rooney'

In [114]:
dic

{'1': 'Ronaldo', '2': 'Rooney', '3': 'Neymar', '4': 'Bruno'}

In [117]:
skills_1 = {'Speed':'90'}
skills_2 = {'Shooting':'89'}
skills_3 = {'Dribbling':'92'}
skills_4 = {'Passing':'90'}
players= {'player1': skills_1, 'player2': skills_2, 'player3':skills_3, 'player4':skills_4}

In [119]:
print(players)

{'player1': {'Speed': '90'}, 'player2': {'Shooting': '89'}, 'player3': {'Dribbling': '92'}, 'player4': {'Passing': '90'}}


In [120]:
print(players['player3'])

{'Dribbling': '92'}


# Tuple

In [123]:
tup = ('ManUnited','ManCity','RealMadrid', 'ManUnited')
tup.count('ManUnited')

2

In [125]:
tup.index('RealMadrid')

2

# Numpy

In [7]:
import numpy as np

In [8]:
my_lst = [1,3,5,7,9]
type(my_lst)
#print(my_lst)

list

In [9]:
arr = np.array(my_lst)
type(arr)

numpy.ndarray

In [10]:
print(arr)

[1 3 5 7 9]


In [11]:
arr.shape

(5,)

In [12]:
arr1 = [1,2,3,4,5]
arr2 = [2,4,6,8,10]
arr3 = [1,3,5,7,9]

arry = np.array([arr1,arr2,arr3])

In [13]:
arry.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# Indexing

In [14]:
arry[2][3]

7

In [15]:
arry[2:,1:3]

array([[3, 5]])

In [16]:
ary = np.arange(5,25,step=3)
ary

array([ 5,  8, 11, 14, 17, 20, 23])

# Pandas

In [35]:
import pandas as pd

In [36]:
df= pd.DataFrame(np.arange(0,20).reshape(4,5), index=['row1', 'row2','row3','row4'], columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [37]:
df.to_csv('sample.csv')

In [38]:
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
col5    4
Name: row1, dtype: int32

In [39]:
type(df.loc['row2'])

pandas.core.series.Series

In [40]:
df.iloc[2:,3:]

col4  col5
row3    13    14
row4    18    19

In [41]:
type(df.iloc[2:,3:])

pandas.core.frame.DataFrame

In [42]:
df.iloc[2:,3:].values

array([[13, 14],
       [18, 19]])

In [43]:
df['col1'].value_counts()

15    1
5     1
10    1
0     1
Name: col1, dtype: int64

In [44]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64

In [64]:
df['col1'].unique()

array([ 0,  5, 10, 15])

In [65]:
df1 = pd.read_csv("netflix_titles.csv")

In [66]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB


In [67]:
# There is no point using .describe for this csv file. 
# Just in case if you wonder, why I can see only 1 column, the reason is in the whole dataset there is only one int column
# every other columns are object/ categorical based.
df1.describe()

release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [69]:
df1['release_year'].value_counts()

2018    1121
2017    1012
2019     996
2016     882
2020     868
        ... 
1966       1
1947       1
1959       1
1964       1
1925       1
Name: release_year, Length: 73, dtype: int64

## Different Example

In [73]:
df2 = pd.read_csv('sample.csv', sep=';', usecols=['col1','col4'], dtype=object)
# If I will give dtype=float/int here, it will give me an error. 
# Why?
# Because, in our dataframe we have names of the rows as: row1, 2,3 4 and hence as it is a object it will give as an error.
#So, we will try it in another way
df1

col1 col4
row1    0    3
row2    5    8
row3   10   13
row4   15   18

In [76]:
df2 = pd.read_csv('sample.csv', sep=';', usecols=['col1','col4'], dtype={'col1':int, 'col4':float})

In [81]:
# See the result now..............
# We can give different datatype to different columns
df2

col1  col4
row1     0   3.0
row2     5   8.0
row3    10  13.0
row4    15  18.0

In [82]:
# If you want to remove the first column:row1,2,3..... then, add index_col=0 in pd.read_csv()
# When there is already a data/seq in the dataset, and more upon that we have column name such as row1,2,3 at 
#that time index_col=0 is useful.... Example: pd.read_csv(blahhhhblahhh, index_col=0 )

In [83]:
data = 'x,y\n"Hello, \\" "Modiji\\, How are you?", 1'

In [85]:
from io import StringIO
pd.read_csv(StringIO(data), escapechar='\\')

x  y
0  Hello, " Modiji, How are you?"  1